# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'dracula/tmux'

set -g @dracula-plugins "cpu-usage ram-usage weather git" 
set -g @dracula-cpu-usage-colors "dark_gray green"
set -g @dracula-ram-usage-colors "dark_gray cyan"
# These are the default values used inside the plugin to achieve the preview shown above.
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-powerline-bg-transparent true
set -g @dracula-show-fahrenheit false 
set -g @dracula-show-location false
set -g @dracula-refresh-rate 2 

set -g base-index 1
setw -g pane-base-index 1
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/tpm/plugins/tpm/tpm'
